name: Build and deploy iOS
on:
  push:
    branches: [ios]

jobs:
  build-and-upload:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo gem install fastlane
          brew install match

      - name: Build and Upload
        env:
          APP_IDENTIFIER: your.app.bundle.id
          APPLE_ID: your@apple.id
          TEAM_ID: your.team.id
          APP_ID: your-app-id
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          fastlane match appstore
          fastlane ios build_ios
          fastlane ios upload_to_firebase
