name: Build Android
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: yarn install
        
      - name: Build Android Release
        run: cd android && ./gradlew assembleRelease
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: android/app/build/outputs/apk/release/app-release.apk

      # - name: list files
      #   run: ls -lrt android/app/build/outputs/apk/release

  # firebase-distribution:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: release
  #     - name: upload artifact to Firebase App Distribution
  #       uses: wzieba/Firebase-Distribution-Github-Action@v1
  #       with:
  #         appId: ${{secrets.FIREBASE_APP_ID_ANDROID}}
  #         token: ${{secrets.FIREBASE_TOKEN}}
  #         groups: Testers
  #         file: app-release.apk
          
  # upload-appStore:
  #   needs: firebase-distribution
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: release
  #     - name: Google Play Store upload
  #       uses: r0adkll/upload-google-play@v1
  #       with:
  #         serviceAccountJson: ${{ secrets.GOOGLE_PLAY_STORE_JSON }}
  #         packageName: com.blueprint
  #         track: internal
  #         releaseFiles: app-release.apk
  #         releaseName: v1.0.0
  #         status: inProgress
  #         userFraction: 0.33
          
#       - name: Upload Artifact
#         uses: actions/upload-artifact@v1
#         with:
#           name: release
#           path: android/app/build/outputs/apk/release/app-release.apk

#       - name: Deploy to Firebase
#         uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
#         with:
#           token: ${{secrets.FIREBASE_TOKEN}}
#           file: android/app/build/outputs/apk/release/app-release.apk
