name: Build and deploy iOS
on:
  push:
    branches: [main]

jobs:
  testFlight-build:
    name: Build-IOS
    runs-on: macos-latest
    
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
     
      - name: Checkout to git repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          yarn install
      
      - name: Install Fastlane
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      
      - name: Install Fastlane
        run: |
          bundle install
          bundle update fastlane

      - name: Install Dependencies
        run: |
          sudo gem install fastlane
          brew install match

      - name: Build and Upload
        env:
          APP_IDENTIFIER: your.app.bundle.id
          APPLE_ID: your@apple.id
          TEAM_ID: your.team.id
          APP_ID: your-app-id
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          fastlane match appstore
          fastlane ios build_ios
          fastlane ios upload_to_firebase