name: Build and deploy iOS
on:
  push:
    branches: [ios]

jobs:
  testFlight-build:
    name: Build-IOS
    runs-on: macos-latest
    
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
     
      - name: Checkout to git repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          yarn install
      
      - name: Install Fastlane
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      
      - name: Install Fastlane
        run: |
          bundle install
          bundle update fastlane
      
      - name: Build and upload to TestFlight
        run: |
          bundle exec fastlane ios beta
          env: 
             APPLE_ID: ${{ secrets.APPLE_ID }}
             APP_STORE_EMAIL: ${{ secrets.APP_STORE_EMAIL }}
             APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
             IOS_DISTRIBUTION_CERTS_GITHUB_URL: ${{ secrets.IOS_DISTRIBUTION_CERTS_GITHUB_URL }}
             MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
